# release
logsql:                       false
port:                         {{prodport}}
JwtSignKey:                   xxxxxxxx_release
dbdriver:                     postgres
connectionstring:             user={{dbname}} password={{dbpassword}} dbname={{dbname}} host=localhost port=5432 sslmode=disable

token.expire.minutes:         120

wechat.enable:                false
wechat.app.appid:             xxxxxxx
wechat.app.secret:            xxxxxxxxxxxxxxx

wechat.getaccesstoken.url:    https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=%s&secret=%s
wechat.sendmessage.url:       https://api.weixin.qq.com/cgi-bin/message/wxopen/template/uniform_send?access_token=%s
