# release
port:                         {{prodport}}
JwtSignKey:                   xxxxxxxx_release
dbdriver:                     postgres
connectionstring:             user={{name}} password={{name}} dbname={{name}} host=localhost port=5432 sslmode=disable

token.expire.minutes:         120

wechat.app.appid:             xxxxxxx
wechat.app.secret:            xxxxxxxxxxxxxxx
